// URI routing for the ATC collection — the two-space scheme from
// W3C "Cool URIs don't change" (https://www.w3.org/Provider/Style/URI):
//
//   canonical  the designed, permanent space. No wp-content, no /category/,
//              no /author/, no .htm, no collision suffixes. Sitemaps and
//              rel=canonical point here and nowhere else.
//   alias      every historical path from both site generations (FrontPage
//              1998-2015, WordPress 2016-2026), permanently 301'd into
//              canonical. Entries are NEVER deleted — that is the policy.
//
// R2 keys stay the unchanged old paths: the URI is decoupled from storage
// rather than storage renamed to match. route_map.json is generated by
// scripts/atc_canonical_map.py; these functions are pure so both hostnames and
// the test suite share one source of truth.

import ROUTES from "./route_map.json" with { type: "json" };

export const PREFIX = "/atc";
export const INDEX_NAMES = ["index.html", "index.htm", "Default.htm"];
const { rules: RULES, alias: ALIAS, key: KEYS, drop: DROP } = ROUTES;

export const GONE_RE =
  /^\/(wp-admin(\/|$)|wp-login\.php|xmlrpc\.php|wp-cron\.php|wp-json(\/|$)|forum(\/|$))/;

// Old site path -> canonical URI, or null when the path is already canonical
// (or unknown). Both slash spellings are tried so a request that arrives AT the
// canonical URI resolves to itself and gets served instead of redirected.
export function canonicalOf(inner) {
  if (ALIAS[inner]) return ALIAS[inner];
  const alt = inner.endsWith("/") ? inner.slice(0, -1) : inner + "/";
  if (ALIAS[alt]) return ALIAS[alt];
  for (const [oldP, newP] of RULES)
    if (inner.startsWith(oldP)) return newP + inner.slice(oldP.length);
  return null;
}

// Canonical URI -> R2 keys to probe, in order. Mirrors resolve_key() in
// scripts/atc_canonical_map.py — keep the two in lockstep.
export function keyCandidates(canon) {
  const exact = KEYS[canon];
  if (exact !== undefined)
    return exact.endsWith("/") ? INDEX_NAMES.map((n) => exact + n) : [exact];
  let inner = canon.startsWith(PREFIX) ? canon.slice(PREFIX.length) : canon;
  for (const [oldP, newP] of RULES) {
    const cn = newP.slice(PREFIX.length);
    if (inner.startsWith(cn)) {
      inner = oldP + inner.slice(cn.length);
      break;
    }
  }
  const base = inner === "/" ? "" : inner.replace(/^\/+/, "").replace(/\/+$/, "");
  if (canon.endsWith("/") || base === "")
    return INDEX_NAMES.map((n) => (base ? `${base}/${n}` : n));
  // A path carrying a format extension is a file, full stop — no index probing.
  if (/\.[a-z0-9]{1,5}$/i.test(base)) return [base];
  return [base, `${base}/index.html`, `${base}/index.htm`,
          `${base}/Default.htm`, `${base}.htm`, `${base}.html`];
}

// Where does an old site path belong? Returns {status} for a tombstone, {to}
// for a 301 target, or null to fall through to serving. Shared by both
// hostnames so atchistory.org/X and archive.aero/atc/X agree, and so a stale
// link costs exactly ONE hop from either direction.
export function routeOldPath(path) {
  const alt = path.endsWith("/") ? path.slice(0, -1) : path + "/";
  const dropped = DROP[path] ?? DROP[alt];
  if (dropped === "410") return { status: 410 };
  if (dropped) return { to: dropped };
  if (GONE_RE.test(path)) return { status: 410 };
  // Per-post and per-category comment feeds are gone; the site feed survives as
  // a frozen snapshot at the canonical /atc/feed (both spellings must pass).
  // Serialization variants of the SITE feed (/feed/atom/ etc, log-discovered
  // 2026-08-30) are the same resource — one hop to the frozen feed, not a 410.
  if (/^\/feed\/(atom|rdf|rss2?)\/?$/i.test(path)) return { to: PREFIX + "/feed" };
  if (path !== "/feed/" && path !== "/feed" && /\/feed\/?$/.test(path))
    return { status: 410 };
  const canon = canonicalOf(path);
  if (canon && canon !== PREFIX + path) return { to: canon };
  return null;
}
