// URI routing for the ATC collection — the two-space scheme from
// W3C "Cool URIs don't change" (https://www.w3.org/Provider/Style/URI):
//
//   canonical  the designed, permanent space. No wp-content, no /category/,
//              no /author/, no .htm, no collision suffixes. Sitemaps and
//              rel=canonical point here and nowhere else.
//   alias      every historical path from both site generations (FrontPage
//              1998-2015, WordPress 2016-2026), permanently 301'd into
//              canonical. Entries are NEVER deleted — that is the policy.
//
// R2 keys stay the unchanged old paths: the URI is decoupled from storage
// rather than storage renamed to match. route_map.json is generated by
// scripts/atc_canonical_map.py; these functions are pure so both hostnames and
// the test suite share one source of truth.

import ROUTES from "./route_map.json" with { type: "json" };

export const PREFIX = "/atc";
export const INDEX_NAMES = ["index.html", "index.htm", "Default.htm"];
const { rules: RULES, alias: ALIAS, key: KEYS, drop: DROP } = ROUTES;
// Every canonical URI the map knows (alias targets + explicit keys): a path
// that IS canonical is served, never redirected by the shape rules below.
const CANON = new Set([...Object.values(ALIAS), ...Object.keys(KEYS)]);

export const GONE_RE =
  /^\/(wp-admin(\/|$)|wp-login\.php|xmlrpc\.php|wp-cron\.php|wp-json(\/|$)|forum(\/|$))/;

// Old site path -> canonical URI, or null when the path is already canonical
// (or unknown). Both slash spellings are tried so a request that arrives AT the
// canonical URI resolves to itself and gets served instead of redirected.
export function canonicalOf(inner) {
  if (ALIAS[inner]) return ALIAS[inner];
  const alt = inner.endsWith("/") ? inner.slice(0, -1) : inner + "/";
  if (ALIAS[alt]) return ALIAS[alt];
  for (const [oldP, newP] of RULES)
    if (inner.startsWith(oldP)) return newP + inner.slice(oldP.length);
  return null;
}

// Canonical URI -> R2 keys to probe, in order. Mirrors resolve_key() in
// scripts/atc_canonical_map.py — keep the two in lockstep.
export function keyCandidates(canon) {
  const exact = KEYS[canon];
  if (exact !== undefined)
    return exact.endsWith("/") ? INDEX_NAMES.map((n) => exact + n) : [exact];
  let inner = canon.startsWith(PREFIX) ? canon.slice(PREFIX.length) : canon;
  for (const [oldP, newP] of RULES) {
    const cn = newP.slice(PREFIX.length);
    if (inner.startsWith(cn)) {
      inner = oldP + inner.slice(cn.length);
      break;
    }
  }
  const base = inner === "/" ? "" : inner.replace(/^\/+/, "").replace(/\/+$/, "");
  if (canon.endsWith("/") || base === "")
    return INDEX_NAMES.map((n) => (base ? `${base}/${n}` : n));
  // A path carrying a format extension is a file, full stop — no index probing.
  if (/\.[a-z0-9]{1,5}$/i.test(base)) return [base];
  return [base, `${base}/index.html`, `${base}/index.htm`,
          `${base}/Default.htm`, `${base}.htm`, `${base}.html`];
}

// Canonical-shaped path -> its old spelling under the prefix rules
// (/history/X -> /History/X, /class-photos/X -> /classphotos/X), or null when
// no rule applies. The inverse of canonicalOf's rule step.
function oldShapeOf(path) {
  for (const [oldP, newP] of RULES) {
    const cn = newP.slice(PREFIX.length);
    if (path.startsWith(cn)) return oldP + path.slice(cn.length);
  }
  return null;
}

// Apache's DirectorySlash, for the rule-derived trees: a directory answered
// by its index file is served at the slashed URI only, so the page's relative
// links resolve inside it. /atc/history/FacilityPhotos used to serve the
// listing whose "ak/" then resolved to /atc/history/ak/ -- a 404 (Search
// Console, 2026-09-20). Map canonicals such as /atc/History are permanent and
// exempt; their listings carry absolute links instead (atc_gen_indexes.py).
export function isDirIndexKey(key) {
  return INDEX_NAMES.some((n) => key.endsWith("/" + n));
}

export function wantsDirectorySlash(canon, key) {
  return !canon.endsWith("/") && !CANON.has(canon) && isDirIndexKey(key);
}

// Keys that would answer the slashed form and were not already probed for the
// slashless one. Non-empty only when a rule changes the directory's own
// spelling (/atc/images -> Images/index.html): the bare probe, which maps
// rules by "/atc/images/" prefix, never finds those. Files (extension) and
// map canonicals never qualify.
export function slashedOnlyCandidates(canon) {
  if (canon.endsWith("/") || CANON.has(canon)) return [];
  const tried = keyCandidates(canon);
  if (!tried.some(isDirIndexKey)) return [];
  const seen = new Set(tried);
  return keyCandidates(canon + "/").filter((k) => !seen.has(k));
}

// Where does an old site path belong? Returns {status} for a tombstone, {to}
// for a 301 target, or null to fall through to serving. Shared by both
// hostnames so atchistory.org/X and archive.aero/atc/X agree, and so a stale
// link costs exactly ONE hop from either direction.
export function routeOldPath(path) {
  const alt = path.endsWith("/") ? path.slice(0, -1) : path + "/";
  // Drops are keyed by old spelling, but the request may arrive in canonical
  // shape: the old host's own 301 of an unknown path prefixes it through the
  // rules, and that is the spelling crawlers keep. Without the second lookup
  // /atc/history/X/dead.htm 404'd while /atc/History/X/dead.htm redirected
  // (Search Console, 2026-09-14).
  const oldShape = oldShapeOf(path);
  const oldAlt = oldShape &&
    (oldShape.endsWith("/") ? oldShape.slice(0, -1) : oldShape + "/");
  const dropped = DROP[path] ?? DROP[alt] ??
    (oldShape ? DROP[oldShape] ?? DROP[oldAlt] : undefined);
  if (dropped === "410") return { status: 410 };
  if (dropped) return { to: dropped };
  if (GONE_RE.test(path)) return { status: 410 };
  // Per-post and per-category comment feeds are gone; the site feed survives as
  // a frozen snapshot at the canonical /atc/feed (both spellings must pass).
  // Serialization variants of the SITE feed (/feed/atom/ etc, log-discovered
  // 2026-08-30) are the same resource — one hop to the frozen feed, not a 410.
  if (/^\/feed\/(atom|rdf|rss2?)\/?$/i.test(path)) return { to: PREFIX + "/feed" };
  if (path !== "/feed/" && path !== "/feed" && /\/feed\/?$/.test(path))
    return { status: 410 };
  const canon = canonicalOf(path);
  if (canon && canon !== PREFIX + path) return { to: canon };
  // A path that IS a canonical URI is served, whatever shape it has; its
  // other slash spelling is an alias of it (one hop).
  if (CANON.has(PREFIX + path)) return null;
  if (CANON.has(PREFIX + alt)) return { to: PREFIX + alt };
  const trimmed = path.endsWith("/") ? path : path + "/";
  // The same page requested in canonical SHAPE but old spelling
  // (/atc/class-photos/PhotoHome.htm, /atc/history/checklst.htm): the alias
  // table is keyed by the old spelling, so without this lookup the serving
  // side found the R2 key through keyCandidates and answered 200 at a
  // non-canonical URI — the curated page living twice (2026-09-08 audit).
  // Only explicit alias entries apply; rule-derived paths (the FrontPage
  // tree's own .htm files) are canonical in their rule-mapped spelling.
  if (oldShape) {
    const c2 = ALIAS[oldShape] ?? ALIAS[oldAlt];
    if (c2 && c2 !== PREFIX + path) return { to: c2 };
  }
  // A rule directory's root in its new spelling (/atc/history, /atc/history/,
  // /atc/class-photos ...) is an alias of the canonical the map gave the old
  // directory (/atc/History ...): one hop to one canonical, instead of a 404
  // for the slashless form and a second 200 for the slashed one.
  for (const [oldP, newP] of RULES) {
    if (trimmed === newP.slice(PREFIX.length)) {
      const c3 = ALIAS[oldP] ?? ALIAS[oldP.slice(0, -1)];
      if (c3 && c3 !== PREFIX + path) return { to: c3 };
    }
  }
  // The site root named as a file is the landing page: /atc/index.html -> /atc/
  if (/^\/(index\.html?|Default\.htm)$/i.test(path)) return { to: PREFIX + "/" };
  return null;
}
