import test from 'node:test';
import assert from 'node:assert/strict';
import {Scheduler} from '../scheduler.js';
import {ByteLRU} from '../lru.js';
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
function harness() {const requests=[],events=[],errors=[],timers=[]; const clock={now:()=>0,setTimeout:(fn,ms)=>{const t={fn,ms};timers.push(t);return t;},clearTimeout:t=>{t.cancelled=true;}};const fetch=(_url,{signal})=>new Promise((resolve,reject)=>{const r={signal,resolve,reject};requests.push(r);signal.addEventListener('abort',()=>reject(signal.reason));});const s=new Scheduler({fetch,concurrency:1,clock,onResult:(r,b)=>events.push([r.key,b]),onError:e=>errors.push(e)});return {s,requests,events,errors,timers};}
const req=(key,priority=1,distance=0)=>({key,url:key,priority,distance});
test('priority, centre order and dedupe',async()=>{const h=harness();h.s.setDemand([req('full',1),req('far',0,5),req('near',0,0),req('near',2)]);assert.equal(h.requests.length,1);h.requests[0].resolve(new Response('a'));await flush();assert.equal(h.events[0][0],'near');h.requests[1].resolve(new Response('b'));await flush();assert.equal(h.events[1][0],'far');h.requests[2].resolve(new Response('c'));await flush();assert.equal(h.events[2][0],'full');assert.equal(h.requests.length,3);h.s.destroy();});
test('demand cancels running and queued, preserves shared jobs',async()=>{const h=harness();h.s.setDemand([req('a'),req('b')]);h.s.setDemand([req('a'),req('c')]);assert.equal(h.requests.length,1);h.s.setDemand([req('c')]);assert.equal(h.requests[0].signal.aborted,true);await flush();assert.equal(h.requests.length,2);h.requests[1].resolve(new Response('ok'));await flush();assert.deepEqual(h.events.map(e=>e[0]),['c']);assert.equal(h.s.stats().cancelled,1);h.s.destroy();});
test('retry twice with fake clock, failure cannot poison later demand',async()=>{const h=harness();h.s.setDemand([req('a')]);for(let i=0;i<3;i++){h.requests[i].resolve(new Response('',{status:503}));await flush();if(i<2){assert.equal(h.timers[i].ms,150*2**i);h.timers[i].fn();await flush();}}assert.equal(h.errors.length,1);assert.equal(h.s.cache.bytes,0);h.s.setDemand([req('a')]);h.requests[3].resolve(new Response('yes'));await flush();assert.equal(h.events.length,1);h.s.destroy();});
test('404 is not retried or cached; transient fetch failure retries',async()=>{const h=harness();h.s.setDemand([req('a')]);h.requests[0].resolve(new Response('',{status:404}));await flush();assert.equal(h.errors.length,1);assert.equal(h.timers.length,0);h.s.setDemand([req('a')]);h.requests[1].reject(new TypeError('network'));await flush();assert.equal(h.timers.length,1);h.s.destroy();assert.equal(h.timers[0].cancelled,true);});
test('204 remembered and success bytes reused without network',async()=>{const h=harness();h.s.setDemand([req('a')]);h.requests[0].resolve(new Response(null,{status:204}));await flush();h.s.setDemand([]);h.s.setDemand([req('a')]);assert.equal(h.requests.length,1);assert.equal(h.events[1][1],null);h.s.destroy();});
test('byte LRU enforces budget and least-recently-used order',()=>{const c=new ByteLRU(4);c.set('a',new Uint8Array(2));c.set('b',new Uint8Array(2));c.get('a');c.set('c',new Uint8Array(2));assert.equal(c.get('b'),undefined);assert.equal(c.bytes,4);c.set('large',new Uint8Array(8));assert.equal(c.bytes,4);});
