import test from 'node:test';
import assert from 'node:assert/strict';
import {Scheduler} from '../scheduler.js';
import {ByteLRU} from '../lru.js';
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
function harness(options={}) {const requests=[],events=[],errors=[],timers=[]; const clock={now:()=>0,setTimeout:(fn,ms)=>{const t={fn,ms};timers.push(t);return t;},clearTimeout:t=>{t.cancelled=true;}};const fetch=(_url,{signal})=>new Promise((resolve,reject)=>{const r={signal,resolve,reject};requests.push(r);signal.addEventListener('abort',()=>reject(signal.reason));});const s=new Scheduler({fetch,concurrency:1,clock,timeout:0,onResult:(r,b)=>events.push([r.key,b]),onError:e=>errors.push(e),...options});return {s,requests,events,errors,timers};}
const req=(key,priority=1,distance=0)=>({key,url:key,priority,distance});
test('priority, centre order and dedupe',async()=>{const h=harness();h.s.setDemand([req('full',1),req('far',0,5),req('near',0,0),req('near',2)]);assert.equal(h.requests.length,1);h.requests[0].resolve(new Response('a'));await flush();assert.equal(h.events[0][0],'near');h.requests[1].resolve(new Response('b'));await flush();assert.equal(h.events[1][0],'far');h.requests[2].resolve(new Response('c'));await flush();assert.equal(h.events[2][0],'full');assert.equal(h.requests.length,3);h.s.destroy();});
test('demand drops queued jobs; a running one lingers into the byte cache outside the slots and is then served from it',async()=>{
  const h=harness();h.s.setDemand([req('a'),req('b')]);h.s.setDemand([req('a'),req('c')]);assert.equal(h.requests.length,1);
  h.s.setDemand([req('c')]);assert.equal(h.requests[0].signal.aborted,false);assert.deepEqual([h.s.stats().lingering,h.s.stats().inflight,h.s.stats().lingered],[1,1,1]);
  assert.equal(h.requests.length,2); // c started at once beside the lingering a
  h.requests[1].resolve(new Response('ok'));await flush();assert.deepEqual(h.events.map(e=>e[0]),['c']);
  h.requests[0].resolve(new Response('late'));await flush();assert.equal(h.s.stats().lingering,0);assert.equal(h.s.cache.get('a')?.byteLength,4);assert.equal(h.events.length,1);
  h.s.setDemand([req('a')]);assert.equal(h.requests.length,2);assert.deepEqual(h.events.map(e=>e[0]),['c','a']);assert.deepEqual([h.s.stats().cacheHits,h.s.stats().cancelled],[1,0]);h.s.destroy();});
test('a lingering fetch is re-adopted when its key returns; past the allowance the oldest is aborted; destroy aborts the rest',async()=>{
  const h=harness({concurrency:2});h.s.setDemand([req('a'),req('b')]);assert.equal(h.requests.length,2);
  h.s.setDemand([]);assert.deepEqual([h.requests[0].signal.aborted,h.requests[1].signal.aborted],[true,false]);assert.deepEqual([h.s.stats().cancelled,h.s.stats().lingering],[1,1]);
  h.s.setDemand([req('b')]);assert.equal(h.requests.length,2);await flush();assert.deepEqual([h.s.stats().readopted,h.s.stats().lingering,h.s.stats().inflight],[1,0,1]);
  h.requests[1].resolve(new Response('b'));await flush();assert.deepEqual(h.events.map(e=>e[0]),['b']);
  h.s.setDemand([req('c')]);h.s.setDemand([]);assert.equal(h.s.stats().lingering,1);h.s.destroy();assert.equal(h.requests[2].signal.aborted,true);assert.equal(h.s.stats().lingering,0);await flush();assert.equal(h.errors.length,0);});
test('retry twice with fake clock, failure cannot poison later demand',async()=>{const h=harness();h.s.setDemand([req('a')]);for(let i=0;i<3;i++){h.requests[i].resolve(new Response('',{status:503}));await flush();if(i<2){assert.equal(h.timers[i].ms,150*2**i);h.timers[i].fn();await flush();}}assert.equal(h.errors.length,1);assert.equal(h.s.cache.bytes,0);h.s.setDemand([req('a')]);h.requests[3].resolve(new Response('yes'));await flush();assert.equal(h.events.length,1);h.s.destroy();});
test('404 is not retried or cached; transient fetch failure retries',async()=>{const h=harness();h.s.setDemand([req('a')]);h.requests[0].resolve(new Response('',{status:404}));await flush();assert.equal(h.errors.length,1);assert.equal(h.timers.length,0);h.s.setDemand([req('a')]);h.requests[1].reject(new TypeError('network'));await flush();assert.equal(h.timers.length,1);h.s.destroy();assert.equal(h.timers[0].cancelled,true);});
test('204 remembered and success bytes reused without network',async()=>{const h=harness();h.s.setDemand([req('a')]);h.requests[0].resolve(new Response(null,{status:204}));await flush();h.s.setDemand([]);h.s.setDemand([req('a')]);assert.equal(h.requests.length,1);assert.equal(h.events[1][1],null);h.s.destroy();});
test('byte LRU enforces budget and least-recently-used order',()=>{const c=new ByteLRU(4);c.set('a',new Uint8Array(2));c.set('b',new Uint8Array(2));c.get('a');c.set('c',new Uint8Array(2));assert.equal(c.get('b'),undefined);assert.equal(c.bytes,4);c.set('large',new Uint8Array(8));assert.equal(c.bytes,4);});
test('adopted early responses are consumed instead of a second fetch; a rejected one falls back to fetch',async()=>{const h=harness();h.s.adopt('a',Promise.resolve(new Response('early',{headers:{'content-type':'image/png'}})));let reject;h.s.adopt('b',new Promise((_,r)=>reject=r));h.s.setDemand([req('a'),req('b')]);await flush();assert.deepEqual(h.events.map(e=>e[0]),['a']);assert.equal(h.requests.length,0);reject(new TypeError('network'));await flush();assert.equal(h.timers.length,1);h.timers[0].fn();await flush();assert.equal(h.requests.length,1);assert.equal(h.requests[0].signal.aborted,false);h.requests[0].resolve(new Response('late'));await flush();assert.equal(h.events[1][0],'b');h.s.destroy();});
test('Retry-After sets the backoff, capped at five seconds',async()=>{const h=harness();h.s.setDemand([req('a')]);h.requests[0].resolve(new Response('',{status:503,headers:{'retry-after':'1'}}));await flush();assert.equal(h.timers[0].ms,1000);h.timers[0].fn();await flush();h.requests[1].resolve(new Response('',{status:503,headers:{'retry-after':'120'}}));await flush();assert.equal(h.timers[1].ms,5000);h.s.destroy();});
test('a stalled fetch times out, retries with a fresh controller and lingers on demand change until destroy',async()=>{const h=harness({timeout:1000});h.s.setDemand([req('a')]);assert.equal(h.timers[0].ms,1000);const first=h.requests[0].signal;h.timers[0].fn();await flush();assert.equal(first.aborted,true);assert.equal(first.reason.name,'TimeoutError');assert.equal(h.s.stats().retries,1);h.timers[1].fn();await flush();assert.equal(h.requests.length,2);assert.notEqual(h.requests[1].signal,first);h.s.setDemand([]);assert.equal(h.requests[1].signal.aborted,false);assert.equal(h.s.stats().lingering,1);h.s.destroy();assert.equal(h.requests[1].signal.aborted,true);await flush();assert.equal(h.errors.length,0);});
